name: auto-test

on:
  pull_request:
  push:
    branches:
      - main
env:
  GO_VERSION: 1.24
  GOLANGCI_LINT_VERSION: v2.1
permissions:
  contents: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Execute linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: .
  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: go test -race -cover -coverprofile="coverage.txt" ./...
        working-directory: .
      - name: Upload to codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
